### PR TITLE
Adding createPageWithRetry in  CreatePageAsAuthorUserIT

### PR DESCRIPTION
**Pull request by absarasw**
## Description

The changes are required to add createPageWithRetry in CreatePageAsAuthorUserIT which provides the correct response in case of exception.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by absarasw** [comment]
Hi @dulvac, Can you please review and merge the PR?

**Review by dulvac — APPROVED** [review]

**Comment by dulvac** [comment]
@volteanu, Are we ok with this change? It will make 403 a valid response for which the test will now skip rather than fail.

**Comment by volteanu** [comment]
Agree, I think this is the best strategy for now.

**Comment by hameed87** [comment]
@dulvac Could you please merge the PR and release the artifacts, as I don't have the permission to do the same.

**Comment by absarasw** [comment]
@dulvac , Can you merge the PR if it looks okay?

**Comment by dulvac** [comment]
@absarasw , Sorry for the delay. It's now merged

**Pull request merged**
