### PR TITLE
Add Sites Admin sanity tests in ESP

### PR DESCRIPTION
**Pull request by adobre90**
Creating 5 tests that should check the stability of Sites Admin:

Create Asset
Create File
Delete Page (using CQClients deletePage(), instead of deletePath() used in the Page Rule)
Copy Page
Move Page
Create Page and Publish Page are already handled in the general smoke test already put in place. This package does not need test content as it generates pages on the fly, but does need a image in order to test the Asset and File generation/uploading.
I've also ran the tests several times and no flakiness was observed.

### CODE REVIEW

**Comment by adobre90** [comment]
To note that on an older PR, @martinischeery has noted that AssetFileIT tests should be something that should be left to DAM.

**Comment by volteanu** [comment]
@adobre90 as a first feedback:
* can we rename the module to exclude the `ui` part? It might confuse ppl into thinking this is for ui, while it targets only the http API
* since we don't want the asset tests here, can they be removed?
* if we remove the asset tests, the only remaining test class `PageActionIT`. It could be easily moved to  `it.smoke`, unless we plan to soon add more tests for WCM.

**Comment by adobre90** [comment]
@volteanu I've added `PageActionIT` to `it.smoke` as you suggested and also observed that by using the `Page` rule I do not need to add `CleanUpRule`, so I removed it.
Also, I've excluded the assets test case and as such also excluded the test resources the `TempFolder` rule, as it was not needed anymore.

At the moment, this PR only adds 3 tests that checks the basic functionality of the Sites Admin Console.

**Review by volteanu — APPROVED** [review]
@adobre90 LGTM now!

**Review by dulvac — APPROVED** [review]
LGTM but i haven't tested them myself.

**Pull request merged**
